version: 2

updates:
- package-ecosystem: pip
  directory: /
  ignore:
    - dependency-name: "apolo-sdk"
      versions: ['*']
    - dependency-name: "apolo-cli"
      versions: ['*']
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: /apolo-sdk
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: /apolo-cli
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
