version: 2

updates:
- package-ecosystem: pip
  directory: /requirements
  ignore:
    - dependency-name: "neuro-sdk"
    - dependency-name: "neuro-cli"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: /neuro-sdk
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: /neuro-cli
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
