repos:
- repo: local
  hooks:
  - id: version-check
    name: Check the package version
    language: python
    entry: ./build-tools/version.py update
    additional_dependencies: ['click']
    pass_filenames: false
  - id: gen-cli-docs
    name: Generate CLI docs
    language: python
    entry: make docs
    additional_dependencies: ['neuro-cli', 'markdown-toc']
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1'
  hooks:
  - id: check-merge-conflict
    exclude: "rst$"
- repo: https://github.com/asottile/yesqa
  rev: v1.2.3
  hooks:
  - id: yesqa
- repo: https://github.com/aio-libs/sort-all
  rev: v1.1.0
  hooks:
  - id: sort-all
- repo: https://github.com/PyCQA/isort
  rev: '5.9.3'
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: '21.8b0'
  hooks:
  - id: black
    language_version: python3 # Should be a command that runs python3.6+
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1'
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-added-large-files
  - id: end-of-file-fixer
    exclude: "[.]md$"
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: "[.]ref$"
  - id: check-symlinks
  - id: debug-statements
  - id: file-contents-sorter
    files: |
      (?x)^(
        .gitignore|
        neuro-sdk/docs/spelling_wordlist.txt
      )$
- repo: https://github.com/asottile/pyupgrade
  rev: 'v2.25.0'
  hooks:
  - id: pyupgrade
    args: ['--py36-plus']
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.9.2'
  hooks:
  - id: flake8
    exclude: "^neuro-sdk/docs/"
