version: 2
sphinx:
  configuration: apolo-sdk/docs/conf.py
formats: all
python:
  version: 3.8
  install:
    - requirements: requirements/doc.txt
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
