image: Visual Studio 2015

environment:
  matrix:
    - PATH: 'C:\Python36;C:\Python36\Scripts;%PATH%'
    - PATH: 'C:\Python37;C:\Python37\Scripts;%PATH%'
  # GNU make
  MAKE: C:\MinGW\bin\mingw32-make.exe
  CLIENT_TEST_E2E_USER_NAME:
    secure: Ezk747oC7HgZ4TJCSDuYqpXzIqW81gQLHGMWyr2T6B4+DTwY+BQqwSQI1P+JwwKF2Ijf7TQ8RzO4vKnTnfNwh7H/xPLEtR5CCPB1hK1O5ecXWSE4KpsVq3+TLNCOMYSCqvHN6TS/ZmafP1DnGt0Y6Zv0KXPyql+bYATzKZe9I/w=

platform: x64

install:
  # install dev dependencies
  - '%MAKE% init'

build: off

# do not run automatic test discovery
test: off

test_script:
  - '%MAKE% test'
  - '%MAKE% _e2e_win'
  - '%MAKE% coverage'

# will start RDP server you can connect to for remote debugging (a-la ssh in circleci)
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
