[tool.towncrier]
    package = "neuro_cli"
    package_dir = "neuro-cli"
    directory = "CHANGELOG.D"
    filename = "CHANGELOG.md"
    template = "CHANGELOG.D/towncrier_template.md"
    title_format = "Neuro SDK/CLI {version} ({project_date})"
    issue_format = "[#{issue}](https://github.com/neuro-inc/platform-client-python/issues/{issue})"
    start_string = "[comment]: # (towncrier release notes start)\n"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = false
