# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
py36: &py36
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    environment:
      PYTHON_VERSION:3.6.1

py36: &py37
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    environment:
      PYTHON_VERSION:3.7.2

build: &build
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ .Environment.PYTHON_VERSION }}-{{ checksum "requirements/ci.txt" }}-{{ checksum "requirements/base.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip3 install -r requirements/ci.txt

      - save_cache:
          paths:
            - ./.env
          key: v2-dependencies-{{ .Environment.PYTHON_VERSION }}-{{ checksum "requirements/ci.txt" }}-{{ checksum "requirements/base.txt" }}
      - setup_remote_docker
      - run:
          name: run CI target
          command: |
            . .env/bin/activate
            make ci


version: 2
jobs:  
  build_py36:
    <<: *py36
    <<: *build

  build_py37:
    <<: *py37
    <<: *build

  pypi_deploy:
    <<: *py36
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ .Environment.PYTHON_VERSION }}-{{ checksum "requirements/ci.txt" }}-{{ checksum "requirements/base.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            make init

      - run:
          name: pypi upload
          command: |
            . .env/bin/activate
            make publish

      - save_cache:
          paths:
            - ./.env
          key: v2-dependencies-{{ checksum "requirements/ci.txt" }}-{{ checksum "requirements/base.txt" }}

  trigger_e2e:
    <<: *py36
    steps:
      - run:
          name: trigger platform-e2e tests
          command: |
              curl -X POST --header "Content-Type: application/json" \
                   -d '{"branch":"master"}' \
                   https://circleci.com/api/v1.1/project/github/neuromation/platform-e2e/build\?circle-token\=${E2E_CIRCLECI_TOKEN}


workflows:
  version: 2

  main:
    jobs:
      - build_py36:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - build_py37:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - trigger_e2e:
          context: org-global
          filters:
            branches:
              only: master
      - pypi_deploy:
          context: org-global
          requires:
            - build_py36
            - build_py37
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
