# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
py36: &py36
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo

py37: &py37
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo

build: &build
    steps:
      - checkout

      - run:
          name: install python
          command: |
            pyenv versions
            pyenv global 3.7.0

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip3 install -r requirements/ci.txt

      - run:
          name: run linters
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make lint

      - run:
          name: run unit tests
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test

      - run:
          name: run e2e tests
          command: |
            . .venv/bin/activate
            make _e2e

      - run:
          name: upload coverage info to codecov.io
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make coverage


version: 2
jobs:  
  build_py36:
    <<: *py36
    <<: *build

  build_py37:
    <<: *py37
    <<: *build

  pypi_deploy:
    <<: *py36
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            make init

      - run:
          name: pypi upload
          command: |
            . .env/bin/activate
            make publish

  trigger_e2e:
    <<: *py36
    steps:
      - run:
          name: trigger platform-e2e tests
          command: |
              curl -X POST --header "Content-Type: application/json" \
                   -d '{"branch":"master"}' \
                   https://circleci.com/api/v1.1/project/github/neuromation/platform-e2e/build\?circle-token\=${E2E_CIRCLECI_TOKEN}


workflows:
  version: 2

  main:
    jobs:
      - build_py36:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - build_py37:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - trigger_e2e:
          context: org-global
          filters:
            branches:
              only: master
      - pypi_deploy:
          context: org-global
          requires:
            - build_py36
            - build_py37
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
