# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
job_env: &job_env
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo

build:
    steps:
      - &py36_step
        run:
          name: install python
          command: |
            pyenv versions
            pyenv global 3.6.5

      - &py37_step
        run:
          name: install python
          command: |
            pyenv versions
            pyenv global 3.7.0

      - &py_deps_step
        run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip3 install -r requirements/ci.txt

      - &lint_step
        run:
          name: run linters
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make lint

      - &unit_step
        run:
          name: run unit tests
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make test

      - &e2e_step
        run:
          name: run e2e tests
          command: |
            . .venv/bin/activate
            export PYTEST_XDIST_NUM_PROCESSES=64
            make _e2e

      - &cov_step
        run:
          name: upload coverage info to codecov.io
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make coverage


version: 2
jobs:  
  build_py36:
    <<: *job_env
    steps:
      - checkout
      - *py36_step
      - *py_deps_step
      - *lint_step
      - *unit_step
      - *e2e_step
      - *cov_step

  build_py37:
    <<: *job_env
    steps:
      - checkout
      - *py37_step
      - *py_deps_step
      - *lint_step
      - *unit_step
      - *e2e_step
      - *cov_step

  pypi_deploy:
    <<: *job_env
    steps:
      - checkout
      - *py36_step

      - run:
          name: install dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            make init

      - run:
          name: pypi upload
          command: |
            . .env/bin/activate
            make publish

  trigger_e2e:
    <<: *job_env
    steps:
      - run:
          name: trigger platform-e2e tests
          command: |
              curl -X POST --fail --header "Content-Type: application/json" \
                   -d '{"branch":"master"}' \
                   https://circleci.com/api/v1.1/project/github/neuromation/platform-e2e/build\?circle-token\=${E2E_CIRCLECI_TOKEN}


workflows:
  version: 2

  main:
    jobs:
      - build_py36:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - build_py37:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - trigger_e2e:
          context: org-global
          filters:
            branches:
              only: master
      - pypi_deploy:
          context: org-global
          requires:
            - build_py36
            - build_py37
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
