# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
defaults: &defaults
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

version: 2
jobs:  
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "python/requirements/ci.txt" }}-{{ checksum "python/requirements/base.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip3 install -r python/requirements/ci.txt

      - save_cache:
          paths:
            - ./.env
          key: v1-dependencies-{{ checksum "python/requirements/ci.txt" }}-{{ checksum "python/requirements/base.txt" }}
      - run:
          name: run CI target
          command: |
            . .env/bin/activate
            make -C python ci

  devpi_deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: devpi setup
          command: |
            python3 -m venv .env
            . .env/bin/activate
            make -C python -s devpi_setup

      - run:
          name: devpi upload
          command: |
            . .env/bin/activate
            make -C python devpi_upload

  pypi_deploy:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "python/requirements/ci.txt" }}-{{ checksum "python/requirements/base.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            make -C python init

      - run:
          name: pypi upload
          command: |
            . .env/bin/activate
            make -C python publish

      - save_cache:
          paths:
            - ./.env
          key: v1-dependencies-{{ checksum "python/requirements/ci.txt" }}-{{ checksum "python/requirements/base.txt" }}

workflows:
  version: 2

  main:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - devpi_deploy:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - pypi_deploy:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
