image: Visual Studio 2015

environment:
  # ensure Python 3.6 is first in path
  PATH: 'C:\Python37;C:\Python37\Scripts;%PATH%'
  # GNU make
  MAKE: C:\MinGW\bin\mingw32-make.exe

platform: x64

install:
  # install dev dependencies
  - cmd: '%MAKE% init'

# do not run MSBuild
build: false

# do not run automatic test discovery
test: off

build_script:
  - cmd: '%MAKE% test'
