[tool.towncrier]
    package = "neuromation"
    package_dir = "."
    directory = "changelog.d"
    filename = "CHANGELOG.md"
    template = "changelog.d/towncrier_template.rst"

    [[tool.towncrier.section]]
        path = ""

    [[tool.towncrier.section]]
        path = "cli"
        name = "Commandline client"

    [[tool.towncrier.type]]
        directory = "release"
        name = "Release Notes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "Deprecations and Removals"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Misc"
        showcontent = false

