trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
      - '*'
pr:
  autoCancel: true
  branches:
    include:
    - master

schedules:
- cron: "0 6 * * *"
  displayName: "Daily 6AM UTC build"
  branches:
    include:
      - master
  always: true

variables:
- group: twine
- group: e2e
- group: codecov

stages:
- template: stage-lint.yml
- template: stage-unit.yml
- template: stage-e2e.yml
