trigger:
  batch: false
  tags:
    include:
    - v*
pr: none


variables:
- group: twine


stages:
- template: stage-lint.yml
- template: stage-unit.yml
- template: stage-e2e.yml
- stage: deployment
  displayName: "Deploy"
  jobs:
  - job: deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
      displayName: "User Python 3.7"

    - script: |
        make init
      displayName: 'Install dependencies'

    - script: |
        make publish
      displayName: 'PyPI upload'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: $(twine.token)
      
