parameters:
  operation_systems:
  - 'ubuntu'
  - 'windows'
  - 'macos'
  python_versions:
  - '3.6'
  - '3.7'


stages:
- stage: test
  displayName: "Unit"
  jobs:
  - job:
    displayName: " "
    strategy:
      matrix:
        ${{ each py in parameters.python_versions }}:
          ${{ each os in parameters.operation_systems }}:
            ${{ format('Py-{0}-{1}', py, os) }}:
              python.version: ${{ py }}
              image: ${{ format('{0}-latest', os) }}
              PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip

    pool:
      vmImage: $[ variables['image'] ]

    timeoutInMinutes: 30

    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: "Use Python $(python.version)"

    - task: Cache@2
      inputs:
        key: 'pip | "$(Agent.OS)" | "$(python.version)" | requirements/base.txt | requirements/ci.txt'
        path: $(PIP_CACHE_DIR)

    - script: |
        python -m pip install -U pip wheel
      displayName: 'Install prerequirements'

    - script: |
        pip install -r requirements/ci.txt pytest-azurepipelines
        pip install .
        touch .update-deps
      displayName: 'Install dependencies'

    - script: |
        make test
      displayName: 'Run unittests'

    - script: |
        pip install codecov
        python -m codecov -f coverage.xml -X gcov
      displayName: 'Upload coverage reports'
      env:
        CODECOV_TOKEN: $(codecov.token)
