name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Setup Python 3.7
        uses: actions/setup-python@2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -r requirements/ci.txt
      - name: Run linters
        run: |
          make lint
      - name: install spell checker
        run: |
          sudo apt install libenchant-dev
          pip install -r requirements/doc.txt
      - name: Run docs spelling
        run: |
          make api-doc-spelling
  name: unit
    needs:
      lint
    matrix:
      python-version: [3.6, 3.7]
      os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache
        uses: actions/cache@2
        env:
          cache-name: cache-pypi
        with:
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements/*.txt'( }}
          path: ${{ github.workspace}}/.pip
          
      - name: Install dependencies
        run: |
          pip install -U pip wheel codecov
          pip install -r requirements/ci.txt
      - name: Run unittests
        run: |
          make test
      - name: Upload coverage
        run: |
          python -m codecov -f coverage.xml -X gcov
          
      
